### ISSUE TITLE
minimal Python version supported?

### ISSUE THREAD

**Issue by abubelinha** [iterative/PyDrive2#167]
I use to share my scripts between machines with different Python versions ranging from 3.4 to 3.9

As of today, I installed PyDrive2 on a Python 3.4, where I used PyDrive with no troubles.
The installation process raised no errors or warnings at all.

But now I got this error which does not happen if I use old PyDrive project:

```
    from pydrive2.auth import GoogleAuth
  File "c:\python34\lib\site-packages\pydrive2\auth.py", line 520
    config = f"client_{file_format}_file_path"

SyntaxError: invalid syntax
```
Is this just a minor bug, so it's still possible to make PyDrive2 work on Python 3.4 ?
(I don't think so: I changed that line and new issues raised somewhere else)

If not, what's the minimal supported version? 
I think there should be information about this in a couple of places:
- `pip install` should at least raise a warning about the minimal supported Python version
- PyDrive2 documentation should show the same information (maybe it's already there and I missed it?)

Thanks a lot in advance

**Comment by efiop** [comment]
Hey @abubelinha 

Thank you for the feedback. Indeed, we only test python 3.6+. I've created #168 to add a python_required option that will help with that. 

We will likely bump it to 3.7+ soon, as 3.6 has reached EOL.

Regarding the docs, they mostly come from original PyDrive, so we didn't touch them yet. We'll update them in a separate PR.

**Comment by abubelinha** [comment]
Somehow related to this, I wonder if it is possible to check the PyDrive2 installed version from code.

```
import pydrive2
pydrive2.__version__
```
output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pydrive2' has no attribute '__version__'
```

**Comment by efiop** [comment]
@abubelinha You could use importlib.metadata for that: https://docs.python.org/3/library/importlib.metadata.html

**Comment by abubelinha** [comment]
Thanks a lot @efiop 

```
from importlib.metadata import version
version('pydrive2')
```
output:
`'1.14.0'`
